In [14]:
#solution 1 Creating Arrays and Reshaping
import numpy as np
from IPython.display import display

num16= np.arange(1, 17)
display(num16)
num16.reshape(4, 4)  # same size

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [24]:
#solution 2 Using reshape and arange
num10_50 = np.arange(10, 51, 5)
display(num10_50)
num10_50.reshape(3, 3)# ValueError: cannot reshape array of size 9 into shape (2,4)

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [39]:
#solution3 Working with randint
np.random.seed(20)
rand_array = np.random.randint(1, 101, (3, 3))
print(rand_array)

max_value = np.max(rand_array)
min_value = np.min(rand_array)

print(f"Max Value: {max_value}")
print(f"Min Value: {min_value}")


[[100  91  16]
 [ 96  29  91]
 [ 10  21  76]]
Max Value: 100
Min Value: 10


In [51]:
#solution4 Slicing Operations
np.random.seed(20)  # 
array = np.random.randint(0, 21, 10)
print(array)
print(f"5 First value {array[:5]} ")
print(f"array in step 2 {array[::2]}")
print(f"array in reverse {array[::-1]}")


[ 3 15  9 20 11  7  2  0  8 19]
5 First value [ 3 15  9 20 11] 
array in step 2 [ 3  9 11  2  8]
array in reverse [19  8  0  2  7 11 20  9 15  3]


In [67]:
#solution 5 Slicing from a 2D Array
np.random.seed(20)
rand_array1_50 = np.random.randint(1, 51, (4, 5))
print(rand_array1_50)
print()
print(f" line 2 {rand_array1_50[1]}, column num 4 {rand_array1_50[:, 3]}")


[[36 27 16 32 29]
 [27 10 21 12 23]
 [ 8 35 33 41 22]
 [27 27 20 17 39]]

 line 2 [27 10 21 12 23], column num 4 [32 12 41 17]


In [85]:
#solution6
nums15= np.random.randint(0, 101,(15))
display(nums15)
copy_orig = nums15.copy()
print('max', copy_orig.max())  # max
print('min', copy_orig.min())  # min
print('argmax', copy_orig.argmax())
print('argmin', copy_orig.argmin())


array([69,  2, 57, 23, 95, 25, 41,  9, 66, 15, 65, 30, 88, 49, 40],
      dtype=int32)

max 95
min 2
argmax 4
argmin 1


In [89]:
#solution 
np.save('nums15.npy', nums15)

In [93]:
newarray15 = np.load('nums15.npy')
print(newarray15)
n15 = newarray15.copy()
n15 = n15[(n15 % 5 == 0)]
print(n15)

[69  2 57 23 95 25 41  9 66 15 65 30 88 49 40]
[95 25 15 65 30 40]


In [103]:
ay_b50_s10 = newarray15.copy()
print(ay_b50_s10)
ay_b50_s10 = ay_b50_s10[(ay_b50_s10 > 50) | (ay_b50_s10 < 10)]
print(ay_b50_s10)

[69  2 57 23 95 25 41  9 66 15 65 30 88 49 40]
[69  2 57 95  9 66 65 88]
